import 'normalize.css';
import './index.scss';
import 'font-awesome/css/font-awesome.css';
import './modules/header/nav/nav';
import './modules/aside/sub-menu/sub-menu';
import './modules/aside/buttons/buttons';
import './modules/sections/calendar/calendar';
import './modules/sections/dropdown/dropdown';
import './modules/sections/message/message';